import 'package:flutter/material.dart';
void main()=>runApp(MaterialApp(debugShowCheckedModeBanner:false,home:SalesPage()));
class SalesPage extends StatefulWidget{@override _SalesPageState createState()=>_SalesPageState();}
class _SalesPageState extends State<SalesPage>{
  final Map<String,TextEditingController> ct={'sl':TextEditingController(),'name':TextEditingController(),'address':TextEditingController(),'phone':TextEditingController(),'itemName':TextEditingController(),'rate':TextEditingController(),'totalW':TextEditingController(),'voriW':TextEditingController(),'fixedW':TextEditingController(),'customK':TextEditingController(),'vori':TextEditingController(),'ana':TextEditingController(),'rati':TextEditingController(),'point':TextEditingController(),'gram':TextEditingController(),'totalBill':TextEditingController(),'cashPaid':TextEditingController(),'bankPaid':TextEditingController(),'oldGoldDetails':TextEditingController(),'oldGoldPrice':TextEditingController(),'advancePaid':TextEditingController(),'dueAmount':TextEditingController(),'paymentStatus':TextEditingController()};
  String sk='উৎপাদিত নতুন গহনা',sc='২১ ক্যারেট হলমার্ক';
  final List<String> ko=['উৎপাদিত নতুন গহনা','কেনা নতুন গহনা','পুরাতন গহনা','বন্ধকী গহনা','অন্যান্য খাত (নিচে লিখুন)'],co=['১৮ ক্যারেট বাংলা','১৮ ক্যারেট কেডিয়াম','২১ ক্যারেট বাংলা','২১ ক্যারেট কেডিয়াম','২১ ক্যারেট হলমার্ক','২২ ক্যারেট হলমার্ক'];
  List<Map<String,dynamic>> sl=[];
  @override void initState(){super.initState();for(var k in ['vori','ana','rati','point','voriW','fixedW','totalBill','cashPaid','bankPaid','oldGoldPrice','advancePaid']){ct[k]?.addListener(_cal);}}
  void _cal(){
    double v=double.tryParse(ct['vori']!.text)??0,a=double.tryParse(ct['ana']!.text)??0,r=double.tryParse(ct['rati']!.text)??0,p=double.tryParse(ct['point']!.text)??0,vw=double.tryParse(ct['voriW']!.text)??0,fw=double.tryParse(ct['fixedW']!.text)??0;
    double tv=v+(a/16)+(r/96)+(p/960),tg=tv*11.664,tw=(tv*vw)+fw;
    ct['gram']!.text=tg>0?tg.toStringAsFixed(3):'';ct['totalW']!.text=tw>0?tw.toStringAsFixed(2):'';
    double b=double.tryParse(ct['totalBill']!.text)??0,c=double.tryParse(ct['cashPaid']!.text)??0,bk=double.tryParse(ct['bankPaid']!.text)??0,o=double.tryParse(ct['oldGoldPrice']!.text)??0,ad=double.tryParse(ct['advancePaid']!.text)??0;
    double d=b-(c+bk+o+ad);ct['dueAmount']!.text=b>0?d.toStringAsFixed(2):'';ct['paymentStatus']!.text=b>0&&d<=0?'পরিশোধিত':'বাকি আছে';
  }
  void _sub(){
    if(ct['phone']!.text.isEmpty){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('মোবাইল নাম্বার লিখুন!'),backgroundColor:Colors.red));return;}
    setState拨款(){sl.add({'sl':ct['sl']!.text.isEmpty?(sl.length+1).toString():ct['sl']!.text,'date':DateTime.now().toString().substring(0,16),'name':ct['name']!.text,'address':ct['address']!.text,'phone':ct['phone']!.text,'item':ct['itemName']!.text,'carat':sc,'khath':sk=='অন্যান্য খাত (নিচে লিখুন)'?ct['customK']!.text:sk,'wt':'${ct['vori']!.text.isEmpty?"০":ct['vori']!.text} ভরি, ${ct['ana']!.text.isEmpty?"০":ct['ana']!.text} আনা, ${ct['rati']!.text.isEmpty?"০":ct['rati']!.text} রতি, ${ct['point']!.text.isEmpty?"০":ct['point']!.text} পয়েন্ট','gm':ct['gram']!.text,'rt':ct['rate']!.text,'wg':ct['totalW']!.text,'tb':ct['totalBill']!.text,'cp':ct['cashPaid']!.text,'bp':ct['bankPaid']!.text,'od':ct['oldGoldDetails']!.text,'op':ct['oldGoldPrice']!.text,'ap':ct['advancePaid']!.text,'da':ct['dueAmount']!.text,'ps':ct['paymentStatus']!.text});}
    showDialog(context:context,builder:(cx)=>AlertDialog(title:Text('মেমো সফল!'),content:Text('ক্রেতা: ${ct['name']!.text}\nবিল: ৳${ct['totalBill']!.text}'),actions:[TextButton(onPressed:(){Navigator.pop(cx);ct.values.forEach((c)=>c.clear());},child:Text('ঠিক আছে'))]));
  }
  @override Widget build(BuildContext context){
    return Scaffold(
      appBar:AppBar(title:Text('জুয়েলারি বিক্রয় ও হিসাব',style:TextStyle(color:Colors.white)),backgroundColor:Colors.amber,actions:[IconButton(icon:Icon(Icons.list_alt,color:Colors.white),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(cx)=>Scaffold(appBar:AppBar(title:Text('মেমো তালিকা'),backgroundColor:Colors.amber),body:sl.isEmpty?Center(child:Text('কোনো মেমো নেই')):ListView.builder(itemCount:sl.length,itemBuilder:(c,i)=>Card(margin:EdgeInsets.all(8),child:Padding(padding:EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('ক্রমিক: ${sl[i]['sl']} | তারিখ: ${sl[i]['date']}',style:TextStyle(color:Colors.blue,fontWeight:VoidCallback!=null?FontWeight.bold:FontWeight.normal)),Divider(),Text('ক্রেতা: ${sl[i]['name']} | ফোন: ${sl[i]['phone']}'),Text('পণ্য: ${sl[i]['item']} (${sl[i]['carat']}) | খাত: ${sl[i]['khath']}'),Text('ওজন: ${sl[i]['wt']} (${sl[i]['gm']} গ্রাম)',style:TextStyle(color:Colors.amber,fontWeight:FontWeight.bold)),Text('মোট বিল: ৳${sl[i]['tb']} | নগদ: ৳${sl[i]['cp']} | ব্যাংক: ৳${sl[i]['bp']}'),Text('পুরাতন গহনা: ${sl[i]['od']} (৳${sl[i]['op']}) | অগ্রিম: ৳${sl[i]['ap']}'),Text('বাকি: ৳${sl[i]['da']} | স্ট্যাটাস: ${sl[i]['ps']}',style:TextStyle(color:Colors.red,fontWeight:FontWeight.bold))])))))))]),
      body:SingleChildScrollView(padding:EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
        Card(child:Padding(padding:EdgeInsets.all(8),child:Column(children:[TextField(controller:ct['sl'],decoration:InputDecoration(labelText:'১. ক্রমিক নাম্বার')),TextField(controller:ct['name'],decoration:InputDecoration(labelText:'ক্রেতার নাম')),TextField(controller:ct['address'],decoration:InputDecoration(labelText:'ঠিকানা')),TextField(controller:ct['phone'],decoration:InputDecoration(labelText:'মোবাইল নাম্বার'),keyboardType:TextInputType.phone),TextField(controller:ct['itemName'],decoration:InputDecoration(labelText:'২. পণ্যের নাম')),DropdownButtonFormField<String>(value:sc,decoration:InputDecoration(labelText:'ক্যারেট'),items:co.map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(n)=>setState(()=>sc=n!))]))),
        SizedBox(height:10),Text('ওজন হিসাব (রতিসহ উল্লেখ থাকবে):',style:TextStyle(color:Colors.amber,fontWeight:FontWeight.bold)),
        Row(children:[Expanded(child:TextField(controller:ct['vori'],decoration:InputDecoration(labelText:'ভরি'),keyboardType:TextInputType.number)),Expanded(child:TextField(controller:ct['ana'],decoration:InputDecoration(labelText:'আনা'),keyboardType:TextInputType.number)),Expanded(child:TextField(controller:ct['rati'],decoration:InputDecoration(labelText:'রতি'),keyboardType:TextInputType.number)),Expanded(child:TextField(controller:ct['point'],decoration:InputDecoration(labelText:'পয়েন্ট'),keyboardType:TextInputType.number)),Expanded(child:TextField(controller:ct['gram'],readOnly:true,decoration:InputDecoration(labelText:'গ্রাম')))]),
        SizedBox(height:10),TextField(controller:ct['rate'],decoration:InputDecoration(labelText:'সোনার দর (ভরি ৳)'),keyboardType:TextInputType.number),TextField(controller:ct['voriW'],decoration:InputDecoration(labelText:'ভরি মজুরি (৳)'),keyboardType:TextInputType.number),TextField(controller:ct['fixedW'],decoration:InputDecoration(labelText:'ফিক্সড মজুরি (৳)'),keyboardType:TextInputType.number),TextField(controller:ct['totalW'],readOnly:true,decoration:InputDecoration(labelText:'মোট মজুরি (৳)')),
        DropdownButton<String>(value:sk,isExpanded:true,items:ko.map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(n)=>setState(()=>sk=n!)),if(sk=='অন্যান্য খাত (নিচে লিখুন)')TextField(controller:ct['customK'],decoration:InputDecoration(labelText:'খাতের নাম')),
        SizedBox(height:10),Text('বিল ও পেমেন্ট হিসাব:',style:TextStyle(color:Colors.blue,fontWeight:FontWeight.bold)),
        Card(child:Padding(padding:EdgeInsets.all(8),child:Column(children:[TextField(controller:ct['totalBill'],decoration:InputDecoration(labelText:'৩. মোট বিল (৳)'),keyboardType:TextInputType.number),TextField(controller:ct['cashPaid'],decoration:InputDecoration(labelText:'৪. নগদ জমা (৳)'),keyboardType:TextInputType.number),TextField(controller:ct['bankPaid'],decoration:InputDecoration(labelText:'৫. ব্যাংক/মোবাইল ব্যাংক জমা (৳)'),keyboardType:TextInputType.number),TextField(controller:ct['oldGoldDetails'],decoration:InputDecoration(labelText:'৬. পুরাতন স্বর্ণ/রুপা বিবরণ')),TextField(controller:ct['oldGoldPrice'],decoration:InputDecoration(labelText:'পুরাতন স্বর্ণ/রুপার দাম (৳)'),keyboardType:TextInputType.number),TextField(controller:ct['advancePaid'],decoration:InputDecoration(labelText:'৭. অগ্রিম জমা (৳)'),keyboardType:TextInputType.number),TextField(controller:ct['dueAmount'],readOnly:true,decoration:InputDecoration(labelText:'৮. মোট বাকি (৳)')),TextField(controller:ct['paymentStatus'],readOnly:true,decoration:InputDecoration(labelText:'৯. পরিশোধ স্ট্যাটাস'))]))),
        SizedBox(height:15),SizedBox(width:double.infinity,height:45,child:ElevatedButton(onPressed:_sub,child:Text('বিক্রয় নিশ্চিত ও মেমো তৈরি করুন'),style:ElevatedButton.styleFrom(backgroundColor:Colors.amber)))
      ]))
    );
  }
}
