name: sales_app
description: "A professional jewelry sales and calculation POS app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # ডেটাবেজ, লোকাল স্টোরেজ ও নেটওয়ার্কিং
  http: ^1.2.1
  shared_preferences: ^2.3.0
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
